# Generated by Django 4.0.4 on 2022-04-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='titre',
            new_name='nom',
        ),
    ]
